# Generated by Django 3.1.4 on 2021-01-14 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='time_balance',
            field=models.DecimalField(choices=[('4 Hours', '4'), ('6 Hours', '6'), ('3 Hours', '3'), ('5 Hours', '5'), ('7 Hours', '7'), ('1 Hour', '1'), ('2 Hours', '2'), ('8 Hours', '8'), ('Not Specified', '0')], decimal_places=2, default='Not Specified', max_digits=4, max_length=40),
        ),
    ]
