# Generated by Django 3.1.4 on 2021-01-02 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_auto_20210102_2250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='time_balance',
            field=models.DecimalField(choices=[('8 Hours', '8'), ('6 Hours', '6'), ('Not Specified', '0'), ('4 Hours', '4'), ('3 Hours', '3'), ('7 Hours', '7'), ('2 Hours', '2'), ('5 Hours', '5'), ('1 Hour', '1')], decimal_places=2, default='Not Specified', max_digits=4, max_length=40),
        ),
    ]
