# Generated by Django 3.1.4 on 2021-01-13 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_auto_20210110_2154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='time_balance',
            field=models.DecimalField(choices=[('3 Hours', '3'), ('Not Specified', '0'), ('2 Hours', '2'), ('7 Hours', '7'), ('1 Hour', '1'), ('4 Hours', '4'), ('6 Hours', '6'), ('8 Hours', '8'), ('5 Hours', '5')], decimal_places=2, default='Not Specified', max_digits=4, max_length=40),
        ),
    ]
