# Generated by Django 3.1.4 on 2021-01-13 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0008_auto_20210113_2225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='time_balance',
            field=models.DecimalField(choices=[('7 Hours', '7'), ('3 Hours', '3'), ('2 Hours', '2'), ('1 Hour', '1'), ('4 Hours', '4'), ('Not Specified', '0'), ('5 Hours', '5'), ('6 Hours', '6'), ('8 Hours', '8')], decimal_places=2, default='Not Specified', max_digits=4, max_length=40),
        ),
    ]
