# Generated by Django 3.1.4 on 2021-01-13 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0010_auto_20210113_2235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='time_balance',
            field=models.DecimalField(choices=[('4 Hours', '4'), ('1 Hour', '1'), ('5 Hours', '5'), ('3 Hours', '3'), ('7 Hours', '7'), ('Not Specified', '0'), ('6 Hours', '6'), ('8 Hours', '8'), ('2 Hours', '2')], decimal_places=2, default='Not Specified', max_digits=4, max_length=40),
        ),
    ]
