# Generated by Django 3.1.4 on 2021-01-14 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memberships', '0002_auto_20210114_1342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packages',
            name='package_type',
            field=models.CharField(choices=[('Premium', 'prem'), ('Free', 'free')], default='Free', max_length=40),
        ),
    ]
