# Generated by Django 3.1.4 on 2021-01-10 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memberships', '0002_auto_20210102_2250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packages',
            name='package_type',
            field=models.CharField(choices=[('Free', 'free'), ('Premium', 'prem')], default='Free', max_length=40),
        ),
        migrations.AlterField(
            model_name='subscriptions',
            name='valid',
            field=models.BooleanField(default=False),
        ),
    ]
