# Generated by Django 3.1.4 on 2021-01-13 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memberships', '0006_auto_20210113_2238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packages',
            name='package_type',
            field=models.CharField(choices=[('Free', 'free'), ('Premium', 'prem')], default='Free', max_length=40),
        ),
    ]
