# Generated by Django 3.1.4 on 2021-02-03 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memberships', '0008_auto_20210126_1343'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='packages',
            name='slug',
        ),
        migrations.AlterField(
            model_name='packages',
            name='package_type',
            field=models.CharField(choices=[('Premium', 'prem'), ('Free', 'free')], default='Free', max_length=40),
        ),
    ]
