# Generated by Django 3.1.4 on 2021-01-14 01:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('short_description', models.CharField(max_length=100)),
                ('long_description', models.TextField()),
                ('duration', models.CharField(choices=[('0hrs', 'Not Specified'), ('1hrs', '1 Hour'), ('2hrs', '2 Hours'), ('3hrs', '3 Hours'), ('4hrs', '4 Hours'), ('5hrs', '5 Hours'), ('6hrs', '6 Hours'), ('7hrs', '7 Hours'), ('8hrs', '8 Hours')], max_length=10, verbose_name='Duration / Time Payment')),
                ('event_date_time', models.DateTimeField(verbose_name='Event Date and Time')),
                ('event_location_postcode', models.CharField(max_length=10)),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now)),
                ('accepted', models.ManyToManyField(related_name='accepted_notice', to=settings.AUTH_USER_MODEL)),
                ('accepted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='accepted_by', to=settings.AUTH_USER_MODEL)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
