# Generated by Django 3.1.4 on 2021-01-14 13:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('notices', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notice',
            name='accepted',
        ),
        migrations.AddField(
            model_name='notice',
            name='commit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='accepted_notice', to=settings.AUTH_USER_MODEL),
        ),
    ]
