# Generated by Django 3.1.4 on 2021-01-02 23:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('notices', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice',
            name='accepted',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='notice',
            name='duration',
            field=models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Duration / Time Payment'),
        ),
        migrations.AlterField(
            model_name='notice',
            name='event_date_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Event Date and Time'),
        ),
    ]
