# Generated by Django 3.1.4 on 2021-01-14 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notices', '0002_auto_20210114_1342'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notice',
            name='accepted_by',
        ),
    ]
