# Generated by Django 3.1.4 on 2021-01-13 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notices', '0003_auto_20210102_2310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice',
            name='event_date_time',
            field=models.DateTimeField(verbose_name='Event Date and Time'),
        ),
    ]
