# Generated by Django 3.1.4 on 2021-01-14 21:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('notices', '0003_remove_notice_accepted_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice',
            name='commit',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='commit_to_help', to=settings.AUTH_USER_MODEL),
        ),
    ]
