# Generated by Django 3.1.4 on 2021-01-13 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notices', '0004_auto_20210113_2023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice',
            name='duration',
            field=models.CharField(choices=[('7 Hours', '7'), ('3 Hours', '3'), ('6 Hours', '6'), ('2 Hours', '2'), ('5 Hours', '5'), ('1 Hour', '1'), ('8 Hours', '8'), ('4 Hours', '4'), ('Not Specified', '0')], max_length=15, verbose_name='Duration / Time Payment'),
        ),
    ]
