# Generated by Django 3.1.4 on 2021-01-17 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notices', '0004_auto_20210114_2138'),
    ]

    operations = [
        migrations.CreateModel(
            name='Commitments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('short_description', models.CharField(max_length=100)),
                ('long_description', models.TextField()),
            ],
        ),
    ]
