# Generated by Django 3.1.4 on 2021-01-13 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notices', '0005_auto_20210113_2225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice',
            name='duration',
            field=models.CharField(choices=[('7 Hours', '7'), ('3 Hours', '3'), ('2 Hours', '2'), ('1 Hour', '1'), ('4 Hours', '4'), ('Not Specified', '0'), ('5 Hours', '5'), ('6 Hours', '6'), ('8 Hours', '8')], max_length=15, verbose_name='Duration / Time Payment'),
        ),
    ]
