# Generated by Django 3.1.4 on 2021-02-05 23:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notices', '0006_auto_20210203_2218'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Commitments',
        ),
    ]
