# Generated by Django 3.1.4 on 2021-02-11 11:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('notices', '0007_delete_commitments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notice',
            name='event_date_time',
        ),
        migrations.AddField(
            model_name='notice',
            name='event_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Event Date'),
        ),
    ]
