# Generated by Django 3.1.4 on 2021-01-13 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notices', '0008_auto_20210113_2238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice',
            name='duration',
            field=models.CharField(choices=[('0hrs', 'Not Specified'), ('1hrs', '1 Hour'), ('2hrs', '2 Hours'), ('3hrs', '3 Hours'), ('4hrs', '4 Hours'), ('5hrs', '5 Hours'), ('6hrs', '6 Hours'), ('7hrs', '7 Hours'), ('8hrs', '8 Hours')], max_length=10, verbose_name='Duration / Time Payment'),
        ),
    ]
