# Generated by Django 3.1.4 on 2021-02-11 14:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('notices', '0009_auto_20210211_1304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice',
            name='event_date_time',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Event Date'),
        ),
    ]
