# Generated by Django 3.1.4 on 2021-02-11 15:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('notices', '0012_auto_20210211_1514'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice',
            name='event_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Event Date'),
        ),
    ]
