# Generated by Django 3.1.4 on 2021-02-11 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notices', '0013_auto_20210211_1548'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notice',
            name='event_date',
        ),
    ]
