# Generated by Django 3.1.4 on 2021-02-11 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notices', '0015_notice_pref_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice',
            name='pref_date',
            field=models.CharField(max_length=100),
        ),
    ]
