# Generated by Django 3.1.4 on 2021-02-11 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notices', '0016_auto_20210211_1640'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notice',
            name='pref_date',
        ),
    ]
