# Generated by Django 3.1.4 on 2021-02-11 17:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notices', '0017_remove_notice_pref_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='notice',
            name='specify_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
