# Generated by Django 3.1.4 on 2021-02-11 17:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('notices', '0018_notice_specify_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice',
            name='specify_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
