# Generated by Django 3.1.4 on 2021-02-11 17:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notices', '0019_auto_20210211_1715'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice',
            name='specify_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
